baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cole Stowell'
theme = 'devise'
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Cole Stowell"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    title = "About Me"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/"
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"

[params]
  description = ""
  header_title = "Cole Stowell"
  header_subtitle = "CS, specializing in low-level programming, systems design, and mathematics"
  home_image = "images/me.png"
  recent_posts = 5
  [params.style]
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "https://github.com/costowell"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/costowell"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:cole@stowell.pro"
